exports.BattlePokedex = {
megaman:{num:800,species:"Megaman",types:["Techno","Steel"],gender:"N",baseStats:{hp:85,atk:90,def:80,spa:140,spd:85,spe:132},abilities:{0:"Compoundeyes",1:"Android Heart",DW:"Download"},heightm:1.5,weightkg:82.5,color:"Blue",eggGroups:["No Eggs"],otherFormes:["megamanbomb","megamanfire"]},
megamanbomb:{num:800,species:"Megaman-Bomb",basespecies:"Megaman",forme:"Bomb",formeletter:"B",types:["Techno","Normal"],gender:"N",baseStats:{hp:100,atk:130,def:105,spa:90,spd:100,spe:88},abilities:{0:"DynoMIGHT",1:"Android Heart",DW:"Robotic"},heightm:1.5,weightkg:82.5,color:"Purple",eggGroups:["No Eggs"]},
megamanfire:{num:800,species:"Megaman-Fire",basespecies:"Megaman",forme:"Fire",formeletter:"F",types:["Techno","Fire"],gender:"N",baseStats:{hp:85,atk:120,def:70,spa:165,spd:70,spe:118},abilities:{0:"Flash Fire",1:"Android Heart",DW:"Exterminate"},heightm:1.5,weightkg:82.5,color:"Purple",eggGroups:["No Eggs"]},
goku:{num:801,species:"Goku",types:["Fighting","Saiyan"],gender:"N",baseStats:{hp:73,atk:145,def:65,spa:145,spd:65,spe:135},abilities:{0:"Moxie",1:"Saiyan Soul",DW:"Iron Fist"},heightm:1.5,weightkg:82.5,color:"Purple",eggGroups:["No Eggs"],otherFormes:["gokusupersaiyan"]},
gokusupersaiyan:{num:801,species:"Goku-Super-Saiyan",basespecies:"Goku",forme:"Super-Saiyan",formeletter:"S",types:["Fighting","Saiyan"],gender:"N",baseStats:{hp:60,atk:160,def:55,spa:160,spd:55,spe:130},abilities:{0:"Moxie",DW:"Iron Fist"},heightm:1.5,weightkg:82.5,color:"Purple",eggGroups:["No Eggs"]},
raiden:{num:802,species:"Raiden",types:["Techno","Fighting"],gender:"N",baseStats:{hp:85,atk:140,def:90,spa:65,spd:80,spe:150},abilities:{0:"Moxie",1:"No Guard",DW:"Revengance"},heightm:2.2,weightkg:80,color:"Brown",eggGroups:["Monster"]},
metaknight:{num:803,species:"Meta-Knight",types:["Dark","Flying"],gender:"N",baseStats:{hp:75,atk:120,def:70,spa:110,spd:90,spe:115},abilities:{0:"Moxie",1:"No Guard",DW:"Technician"},heightm:2.2,weightkg:80,color:"Brown",eggGroups:["Monster"]},
mario:{num:804,species:"Mario",types:["Fire","Normal"],gender:"F",baseStats:{hp:105,atk:60,def:105,spa:120,spd:90,spe:105},abilities:{0:"Thick Fat",1:"Flash Fire",DW:"Immunity"},heightm:2.2,weightkg:80,color:"Brown",eggGroups:["Monster"]},
villager:{num:805,species:"Villager",types:["Normal","Fighting"],gender:"N",baseStats:{hp:81,atk:117,def:91,spa:107,spd:91,spe:128},abilities:{0:"Mold Breaker",1:"Moxie",DW:"Rivalry"},heightm:1.5,weightkg:82.5,color:"Purple",eggGroups:["No Eggs"],otherFormes:["gokusupersaiyan"]},
villagerc:{num:805,species:"Villager-Collecter",basespecies:"Villager",forme:"Collecter",formeletter:"C",types:["Fighting","Dark"],gender:"N",baseStats:{hp:81,atk:140,def:91,spa:91,spd:91,spe:128},abilities:{0:"Mold Breaker",1:"Moxie",DW:"Rivalry"},heightm:1.5,weightkg:82.5,color:"Purple",eggGroups:["No Eggs"]},
link:{num:806,species:"Link",types:["Normal","Fighting"],gender:"N",baseStats:{hp:70,atk:80,def:95,spa:100,spd:90,spe:130},abilities:{0:"Pure Power",DW:"Moxie"},heightm:2.2,weightkg:80,color:"Brown",eggGroups:["Monster"]},
darklink:{num:807,species:"Dark-Link",types:["Dark","Fighting"],gender:"N",baseStats:{hp:70,atk:125,def:70,spa:110,spd:70,spe:109},abilities:{0:"Cursed Body",DW:"Moxie"},heightm:2.2,weightkg:80,color:"Brown",eggGroups:["Monster"]},
bowser:{num:806,species:"Bowser",types:["Dark","Dragon"],gender:"N",baseStats:{hp:100,atk:108,def:70,spa:130,spd:80,spe:90},abilities:{0:"Exterminate",DW:"Intimidate"},heightm:2.2,weightkg:80,color:"Brown",eggGroups:["Monster"]},
thor:{num:806,species:"Thor",types:["Electric","Fighting"],gender:"N",baseStats:{hp:95,atk:145,def:70,spa:95,spd:100,spe:105},abilities:{0:"Volt Absorb",DW:"Guts"},heightm:2.2,weightkg:80,color:"Brown",eggGroups:["Monster"]}
};


